// Static data for services, products, and partners
// These seed the database and also serve as fallback

export const SERVICES = [
  {
    slug: "government-contracting",
    name: "Government Contract Consulting",
    category: "Consulting",
    shortDesc: "Navigate the complex world of government contracts with expert guidance.",
    description: "We help businesses bid, win, and execute government contracts. From RFP strategy to contract management, our team guides you through every step of the federal procurement process.",
    icon: "Building2",
    benefits: [
      "RFP strategy development and bid writing",
      "SAM.gov registration and compliance",
      "NAICS code selection and capability development",
      "Contract negotiation and management",
      "Subcontracting and teaming arrangements",
    ],
    process: [
      { step: 1, title: "Capability Assessment", desc: "We evaluate your current capabilities and identify contracting opportunities." },
      { step: 2, title: "Strategy Development", desc: "Build a winning RFP response strategy tailored to the opportunity." },
      { step: 3, title: "Proposal Execution", desc: "Draft, review, and submit a compelling, compliant proposal." },
      { step: 4, title: "Contract Management", desc: "Ongoing support through contract execution and performance." },
    ],
  },
  {
    slug: "web-development",
    name: "AI-Optimized Web Development",
    category: "Technology",
    shortDesc: "Build websites that perform for both humans and AI search engines.",
    description: "We design and develop websites optimized for the new era of AI-powered search. From Section 508 accessibility compliance to Core Web Vitals, we build digital presences that win.",
    icon: "Globe",
    benefits: [
      "Section 508 accessibility compliance",
      "AI search engine optimization (AEO)",
      "Core Web Vitals optimization (90+ PageSpeed)",
      "Mobile-first responsive design",
      "Schema.org structured data implementation",
    ],
    process: [
      { step: 1, title: "Discovery & Strategy", desc: "Understand your audience, goals, and competitive landscape." },
      { step: 2, title: "Design & Prototype", desc: "Create wireframes and visual designs aligned with your brand." },
      { step: 3, title: "Development", desc: "Build with modern frameworks, optimized for performance and SEO." },
      { step: 4, title: "Launch & Optimize", desc: "Deploy, monitor, and continuously improve performance." },
    ],
  },
  {
    slug: "data-services",
    name: "Data Services",
    category: "Data & Analytics",
    shortDesc: "Transform raw data into actionable insights with 20 years of expertise.",
    description: "From data engineering to dashboards, we modernize your data infrastructure using industry-leading platforms like Databricks and Snowflake. Federal data modernization is our specialty.",
    icon: "BarChart3",
    benefits: [
      "Data lakehouse architecture (Databricks, Snowflake)",
      "ETL pipeline design and implementation",
      "Business intelligence dashboards",
      "Data governance and quality frameworks",
      "Real-time analytics and reporting",
    ],
    process: [
      { step: 1, title: "Data Maturity Assessment", desc: "Evaluate current data infrastructure, quality, and governance." },
      { step: 2, title: "Architecture Design", desc: "Design a modern, scalable data architecture." },
      { step: 3, title: "Implementation", desc: "Build pipelines, warehouses, and analytics layers." },
      { step: 4, title: "Enablement", desc: "Train your team and establish ongoing data operations." },
    ],
  },
  {
    slug: "automation",
    name: "Automation & Integration",
    category: "Technology",
    shortDesc: "Eliminate manual work and connect your systems intelligently.",
    description: "We automate repetitive processes and integrate disparate systems so your team can focus on high-value work. From simple workflows to complex enterprise integrations.",
    icon: "Zap",
    benefits: [
      "Business process automation",
      "API integration and middleware",
      "No-code/low-code workflow design (Make.com, Power Platform)",
      "RPA (Robotic Process Automation)",
      "Custom integration development",
    ],
    process: [
      { step: 1, title: "Process Mapping", desc: "Document and analyze current workflows to identify automation opportunities." },
      { step: 2, title: "Solution Design", desc: "Design the optimal automation architecture." },
      { step: 3, title: "Build & Test", desc: "Implement automations with rigorous testing." },
      { step: 4, title: "Monitor & Scale", desc: "Track performance and expand automation coverage." },
    ],
  },
  {
    slug: "genai",
    name: "GenAI Solutions",
    category: "AI & GenAI",
    shortDesc: "Harness AI to transform operations and create competitive advantage.",
    description: "We help organizations adopt generative AI strategically — from chatbots and document intelligence to custom AI applications. We bridge the gap between AI potential and practical deployment.",
    icon: "Brain",
    benefits: [
      "AI strategy and readiness assessment",
      "Custom AI chatbot development",
      "Document intelligence and automation",
      "Predictive analytics and ML models",
      "Responsible AI governance frameworks",
    ],
    process: [
      { step: 1, title: "AI Readiness Audit", desc: "Assess your data, infrastructure, and organizational readiness for AI." },
      { step: 2, title: "Use Case Prioritization", desc: "Identify and prioritize AI applications by ROI and feasibility." },
      { step: 3, title: "Pilot Development", desc: "Build and validate an AI pilot with measurable outcomes." },
      { step: 4, title: "Scale & Govern", desc: "Expand successful pilots with responsible AI governance." },
    ],
  },
];

export const PRODUCTS = [
  {
    slug: "cmmc-readiness-assessment",
    title: "CMMC Readiness Assessment",
    shortDesc: "Gap analysis against CMMC Level 1/2 with remediation roadmap.",
    description: "A comprehensive evaluation of your organization's cybersecurity posture against CMMC Level 1 and Level 2 requirements. Receive a detailed gap analysis, risk prioritization, and a 90-day remediation roadmap.",
    includes: [
      "CMMC Level 1/2 gap analysis",
      "Risk-prioritized finding report",
      "90-day remediation roadmap",
      "Executive briefing presentation",
      "30-minute follow-up consultation",
    ],
    deliveryTime: "10–14 business days",
    price: 350000,
    serviceSlug: "government-contracting",
    featured: true,
  },
  {
    slug: "ai-readiness-audit",
    title: "AI Readiness Audit",
    shortDesc: "Evaluate your organization's readiness for AI/GenAI adoption.",
    description: "Assess your organization across three dimensions: data readiness, infrastructure readiness, and talent readiness. Receive a scored maturity model, investment priorities, and a practical AI adoption roadmap.",
    includes: [
      "Three-dimension AI maturity assessment",
      "Scored readiness scorecard",
      "Technology stack recommendations",
      "AI investment priority roadmap",
      "Presentation to leadership team",
    ],
    deliveryTime: "7–10 business days",
    price: 250000,
    serviceSlug: "genai",
    featured: true,
  },
  {
    slug: "data-maturity-assessment",
    title: "Data Maturity Assessment",
    shortDesc: "Score your data governance, quality, architecture, and analytics.",
    description: "A detailed evaluation of your data environment across governance, data quality, architecture, and analytics capabilities. Receive a maturity scorecard benchmarked against industry standards and a phased improvement roadmap.",
    includes: [
      "Data governance maturity scorecard",
      "Data quality evaluation",
      "Architecture assessment",
      "Analytics capability benchmark",
      "Phased improvement roadmap",
    ],
    deliveryTime: "7–10 business days",
    price: 200000,
    serviceSlug: "data-services",
    featured: false,
  },
  {
    slug: "govcon-bid-strategy-package",
    title: "GovCon Bid Strategy Package",
    shortDesc: "RFP response strategy, win themes, and compliance matrix.",
    description: "A complete bid preparation package for a specific government contract opportunity. Includes win theme development, compliance matrix, executive summary framework, and price-to-win analysis guidance.",
    includes: [
      "RFP requirements analysis",
      "Win theme development",
      "Compliance matrix template",
      "Executive summary framework",
      "Price-to-win analysis guidance",
      "Live strategy session (2 hours)",
    ],
    deliveryTime: "5–7 business days",
    price: 150000,
    serviceSlug: "government-contracting",
    featured: true,
  },
  {
    slug: "website-ai-optimization-audit",
    title: "Website AI Optimization Audit",
    shortDesc: "Evaluate your website for AI search readiness, SEO, and conversion.",
    description: "A comprehensive audit of your website's performance in traditional and AI-powered search, along with conversion rate optimization analysis. Receive a prioritized action plan with technical and content recommendations.",
    includes: [
      "AI search readiness evaluation",
      "Technical SEO audit",
      "Core Web Vitals assessment",
      "Conversion optimization analysis",
      "Prioritized action plan (PDF)",
      "Implementation consultation (1 hour)",
    ],
    deliveryTime: "5–7 business days",
    price: 175000,
    serviceSlug: "web-development",
    featured: false,
  },
];

export const PARTNERS = [
  { slug: "databricks", name: "Databricks", category: "Data & AI", serviceTags: ["Data Engineering", "AI/ML", "Lakehouse"], gjhValueAdd: "GJH implements Databricks for federal data modernization and AI/ML pipelines.", portalUrl: "https://www.databricks.com/partners", featured: true },
  { slug: "snowflake", name: "Snowflake", category: "Data & AI", serviceTags: ["Data Warehouse", "Data Sharing", "Analytics"], gjhValueAdd: "GJH migrates and manages Snowflake data cloud environments for government and commercial clients.", portalUrl: "https://www.snowflake.com/partners/", featured: true },
  { slug: "sigma", name: "Sigma Computing", category: "Data & AI", serviceTags: ["Business Intelligence", "Analytics", "Reporting"], gjhValueAdd: "GJH deploys Sigma on top of Snowflake/Databricks for executive dashboards.", portalUrl: "https://www.sigmacomputing.com/partners", featured: true },
  { slug: "nvidia", name: "NVIDIA", category: "Data & AI", serviceTags: ["GPU Infrastructure", "AI Acceleration", "Deep Learning"], gjhValueAdd: "GJH integrates NVIDIA AI infrastructure for GenAI and ML workloads.", portalUrl: "https://www.nvidia.com/en-us/about-nvidia/partners/", featured: true },
  { slug: "aws", name: "AWS", category: "Cloud", serviceTags: ["Cloud Infrastructure", "Migration", "Security"], gjhValueAdd: "GJH delivers AWS cloud migrations, Well-Architected reviews, and managed cloud operations.", portalUrl: "https://aws.amazon.com/partners/", featured: true },
  { slug: "microsoft", name: "Microsoft", category: "Cloud", serviceTags: ["Azure", "Microsoft 365", "Power Platform", "Copilot"], gjhValueAdd: "GJH deploys Azure AI, M365 governance, and Power Platform automations.", portalUrl: "https://partner.microsoft.com/", featured: true },
  { slug: "google", name: "Google", category: "Cloud", serviceTags: ["Google Cloud", "Workspace", "Gemini AI"], gjhValueAdd: "GJH implements GCP data stacks and Google Workspace deployments.", portalUrl: "https://cloud.google.com/find-a-partner", featured: false },
  { slug: "salesforce", name: "Salesforce", category: "Business Operations", serviceTags: ["CRM", "Sales Cloud", "Government Cloud"], gjhValueAdd: "GJH configures and customizes Salesforce for government contractors.", portalUrl: "https://partners.salesforce.com/", featured: false },
  { slug: "zoho", name: "Zoho", category: "Business Operations", serviceTags: ["CRM", "HR", "Finance", "Marketing Automation"], gjhValueAdd: "GJH implements Zoho suite for SMB and mid-market clients.", portalUrl: "https://www.zoho.com/partner/", featured: false },
  { slug: "apollo", name: "Apollo", category: "Business Operations", serviceTags: ["Sales Intelligence", "Prospect Enrichment", "Outbound"], gjhValueAdd: "GJH uses Apollo internally and recommends it for client outbound programs.", portalUrl: "https://www.apollo.io/", featured: false },
  { slug: "mailchimp", name: "MailChimp", category: "Business Operations", serviceTags: ["Email Marketing", "Audience Management"], gjhValueAdd: "GJH implements MailChimp for clients needing accessible email marketing automation.", portalUrl: "https://mailchimp.com/about/affiliates/", featured: false },
  { slug: "make", name: "Make.com", category: "Automation", serviceTags: ["No-Code Automation", "Workflow Integration", "API Connections"], gjhValueAdd: "GJH builds Make.com automations connecting CRMs, ERPs, and data sources.", portalUrl: "https://www.make.com/en/partners", featured: false },
  { slug: "shopify", name: "Shopify", category: "E-Commerce & Web", serviceTags: ["E-Commerce", "Storefront Development"], gjhValueAdd: "GJH builds Shopify stores for government suppliers and commercial clients.", portalUrl: "https://www.shopify.com/partners", featured: false },
  { slug: "wpengine", name: "WP Engine", category: "E-Commerce & Web", serviceTags: ["WordPress Hosting", "Web Performance"], gjhValueAdd: "GJH recommends WP Engine for clients needing managed WordPress hosting.", portalUrl: "https://wpengine.com/partners/", featured: false },
  { slug: "godaddy", name: "GoDaddy", category: "E-Commerce & Web", serviceTags: ["Domains", "DNS Management", "Hosting"], gjhValueAdd: "GJH manages domain portfolios and DNS for clients through GoDaddy.", portalUrl: "https://www.godaddy.com/reseller", featured: false },
  { slug: "zoom", name: "Zoom", category: "Communications", serviceTags: ["Video Conferencing", "Zoom Phone", "AI Companion"], gjhValueAdd: "GJH deploys and manages Zoom for organizations modernizing communications.", portalUrl: "https://www.zoom.com/en/partners/", featured: false },
  { slug: "tawkto", name: "Tawk.to", category: "Communications", serviceTags: ["Live Chat", "Customer Support"], gjhValueAdd: "GJH implements Tawk.to for clients needing real-time visitor engagement.", portalUrl: "https://www.tawk.to/affiliates/", featured: false },
];

export const TESTIMONIALS = [
  {
    name: "Director of IT",
    org: "Federal Civilian Agency",
    quote: "GJH's data modernization work transformed our reporting capabilities. We went from weekly static reports to real-time dashboards in 90 days.",
    rating: 5,
  },
  {
    name: "CEO",
    org: "8(a) Government Contractor",
    quote: "Their bid strategy support helped us win our first $2M federal contract. The RFP process felt manageable for the first time.",
    rating: 5,
  },
  {
    name: "CTO",
    org: "Mid-Market Technology Firm",
    quote: "The AI Readiness Audit gave us a clear, honest picture of where we stood and exactly what to do next. Worth every penny.",
    rating: 5,
  },
];
